# Generated by Django 5.2 on 2025-05-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_beneficiario_alter_cuentabancaria_saldo_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='banco.cuenta'),
        ),
    ]
